import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'ClassArrays/TopicButtonArray.dart';
import 'package:pinch_zoom_image/pinch_zoom_image.dart';

class MTG_Physics_Physics extends StatefulWidget {
  @override
  _MTG_Physics_PhysicsState createState() {
    return new _MTG_Physics_PhysicsState();
  }
}

class _MTG_Physics_PhysicsState extends State<MTG_Physics_Physics> with SingleTickerProviderStateMixin {

  TabController controller;

  @override
  void initState() {

    controller = new TabController(length: 1, vsync: this);

    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return SafeArea(
      child: ClipRRect(
        borderRadius: BorderRadius.only(
            topLeft: Radius.circular(25.0), topRight: Radius.circular(25.0)),
        child: new Scaffold(

          appBar: new TabBar(
            indicatorColor: Colors.black87,
            indicatorSize: TabBarIndicatorSize.label,
            unselectedLabelColor: Colors.grey,
            labelColor: TopicButtonArray().ColorTheme[3],
            controller: controller,

            tabs: <Widget>[
              new Tab(
                icon: new Icon(Icons.description, color:  TopicButtonArray().ColorTheme[1],),
                text:  "View",
              ),


            ],


          ),




          body: new TabBarView(

            controller: controller,
            children: <Widget>[

              new Questions(), //If you calling it from a different page use PageOne.PageOne(),



            ],

          ),


        ),
      ),
    );

  }

}

class Questions extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return  new ListView(

      children: <Widget>[




        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-048.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-049.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-050.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-051.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-052.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-053.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-054.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-055.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-056.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-057.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-058.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-059.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-060.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-061.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-062.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-063.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-064.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-065.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-066.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-067.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-068.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-069.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-070.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-071.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-072.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-073.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-074.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-075.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-076.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-077.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-078.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-079.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-080.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-081.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-082.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-083.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-084.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-085.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-086.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-087.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-088.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-089.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-090.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-091.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-092.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-093.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-094.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-095.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-096.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-097.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-098.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-100.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-101.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-102.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-103.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-104.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-105.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-106.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-107.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-108.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-109.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-110.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-111.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-112.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-113.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-114.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-115.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-116.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-117.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-118.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-119.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-120.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-121.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-122.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-123.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-124.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-125.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-126.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-127.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-128.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-129.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-130.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-131.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-132.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-133.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-134.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-135.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-136.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-137.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-138.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-139.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-140.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-141.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-142.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-143.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-144.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-145.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-146.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-147.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-148.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-149.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-150.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-151.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-152.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-153.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-154.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-155.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-156.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-157.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-158.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-159.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-160.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-161.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-162.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-163.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-164.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-165.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-166.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-167.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-168.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-169.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-170.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-171.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-172.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-173.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-174.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-175.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-176.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-177.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-178.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-179.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-180.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-181.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-182.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-183.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-184.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-185.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-186.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-187.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-188.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-189.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-190.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-191.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-192.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-193.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_PhysicalScience_Physics/MTG_PhysicalScience_Physics-194.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
      ],
    );
  }

}




