import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'ClassArrays/TopicButtonArray.dart';
import 'package:pinch_zoom_image/pinch_zoom_image.dart';

class MTG_LifeScience extends StatefulWidget {
  @override
  _MTG_LifeScienceState createState() {
    return new _MTG_LifeScienceState();
  }
}

class _MTG_LifeScienceState extends State<MTG_LifeScience> with SingleTickerProviderStateMixin {

  TabController controller;

  @override
  void initState() {

    controller = new TabController(length: 1, vsync: this);

    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return SafeArea(
      child: ClipRRect(
        borderRadius: BorderRadius.only(
            topLeft: Radius.circular(25.0), topRight: Radius.circular(25.0)),
        child: new Scaffold(

          appBar: new TabBar(
            indicatorColor: Colors.black87,
            indicatorSize: TabBarIndicatorSize.label,
            unselectedLabelColor: Colors.grey,
            labelColor: TopicButtonArray().ColorTheme[3],
            controller: controller,

            tabs: <Widget>[
              new Tab(
                icon: new Icon(Icons.description, color:  TopicButtonArray().ColorTheme[1],),
                text:  "View",
              ),


            ],


          ),




          body: new TabBarView(

            controller: controller,
            children: <Widget>[

              new Questions(), //If you calling it from a different page use PageOne.PageOne(),



            ],

          ),


        ),
      ),
    );

  }

}

class Questions extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return  new ListView(

      children: <Widget>[

        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-019.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-020.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-021.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-022.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-023.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-024.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-025.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-026.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-027.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-028.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-029.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-030.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-031.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-032.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-033.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-034.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-035.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-036.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-037.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-038.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-039.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-040.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-041.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-042.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-043.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-044.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-045.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-046.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-047.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-048.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-049.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-050.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-051.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-052.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-053.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-054.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-055.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-056.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-057.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-058.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-059.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-060.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-061.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-062.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-063.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-064.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-065.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-066.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-067.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-068.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-069.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-070.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-071.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-072.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-073.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-074.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-075.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-076.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-077.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-078.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-079.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-080.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-081.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-082.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-083.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-084.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-085.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-086.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-087.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-088.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-089.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-090.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-091.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-092.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-093.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-094.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-095.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-096.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-097.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-098.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-100.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-101.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-102.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-103.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-104.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-105.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-106.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-107.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-108.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-109.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-110.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-111.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-112.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-113.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-114.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-115.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-116.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-117.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-118.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-119.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-120.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-121.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-122.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-123.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-124.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-125.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-126.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-127.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-128.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-129.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-130.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-131.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-132.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-133.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-134.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-135.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-136.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-137.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-138.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-139.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-140.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-141.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-142.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-143.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-144.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-145.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-146.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-147.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-148.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-149.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-150.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-151.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-152.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-153.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-154.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-155.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-156.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-157.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-158.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-159.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-160.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-161.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-162.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-163.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-164.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-165.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-166.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-167.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-168.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-169.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-170.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-171.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-172.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-173.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-174.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-175.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-176.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-177.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-178.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_LifeScience/MTG_LifeScience-179.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
       ],
    );
  }

}




