import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'ClassArrays/TopicButtonArray.dart';
import 'package:pinch_zoom_image/pinch_zoom_image.dart';

class MTG_Geography extends StatefulWidget {
  @override
  _MTG_GeographyState createState() {
    return new _MTG_GeographyState();
  }
}

class _MTG_GeographyState extends State<MTG_Geography> with SingleTickerProviderStateMixin {

  TabController controller;

  @override
  void initState() {

    controller = new TabController(length: 2, vsync: this);

    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return SafeArea(
      child: ClipRRect(
        borderRadius: BorderRadius.only(
            topLeft: Radius.circular(25.0), topRight: Radius.circular(25.0)),
        child: new Scaffold(

          appBar: new TabBar(
            indicatorColor: Colors.black87,
            indicatorSize: TabBarIndicatorSize.label,
            unselectedLabelColor: Colors.grey,
            labelColor: TopicButtonArray().ColorTheme[3],
            controller: controller,

            tabs: <Widget>[
              new Tab(
                icon: new Icon(Icons.description, color:  TopicButtonArray().ColorTheme[1],),
                text:  "View",
              ),
              new Tab(
                icon: new Icon(Icons.description, color:  TopicButtonArray().ColorTheme[1],),
                text:  "map",
              ),


            ],


          ),




          body: new TabBarView(

            controller: controller,
            children: <Widget>[

              new Questions(), //If you calling it from a different page use PageOne.PageOne(),
              new Addendum(),


            ],

          ),


        ),
      ),
    );

  }

}

class Questions extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return  new ListView(

      children: <Widget>[


        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-021.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-022.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-023.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-024.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-025.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-026.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-027.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-028.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-029.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-030.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-031.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-032.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-033.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-034.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-035.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-036.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-037.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-038.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-039.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-040.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-041.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-042.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-043.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-044.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-045.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-046.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-047.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-048.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-049.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-050.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-051.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-052.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-053.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-054.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-055.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-056.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-057.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-058.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-059.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-060.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-061.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-062.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-063.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-064.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-065.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-066.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-067.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-068.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-069.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-070.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-071.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-072.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-073.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-074.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-075.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-076.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-077.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-078.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-079.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-080.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-081.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-082.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-083.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-084.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-085.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-086.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-087.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-088.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-089.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-090.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-091.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-092.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-093.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-094.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-095.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-096.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-097.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-098.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-100.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-101.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-102.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-103.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-104.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-105.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-106.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-107.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-108.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-109.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-110.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-111.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-112.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-113.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-114.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-115.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-116.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-117.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-118.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-119.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-120.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-121.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-122.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-123.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-124.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-125.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-126.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-127.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-128.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-129.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-130.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-131.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-132.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-133.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-134.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-135.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-136.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-137.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-138.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-139.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-140.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-141.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-142.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-143.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-144.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-145.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-146.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-147.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-148.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-149.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-150.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-151.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-152.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-153.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-154.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-155.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-156.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-157.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-158.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-159.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-160.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-161.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-162.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-163.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-164.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-165.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-166.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-167.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-168.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-169.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-170.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-171.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-172.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-173.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-174.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-175.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-176.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-177.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-178.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-179.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-180.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-181.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-182.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-183.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-184.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-185.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-186.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-187.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-188.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-189.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-190.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-191.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-192.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-193.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-194.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography/MTG_Geography-195.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),



      ],
    );
  }

}


class Addendum extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return  new ListView(

      children: <Widget>[




        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography_map_1/MTG_Geography_map_1-1.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography_map_1/MTG_Geography_map_1-2.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography_map_1/MTG_Geography_map_1-3.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography_map_1/MTG_Geography_map_1-4.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography_map_1/MTG_Geography_map_1-5.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Geography_map_1/MTG_Geography_map_1-6.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),

      ],
    );
  }

}






