import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'ClassArrays/TopicButtonArray.dart';
import 'package:pinch_zoom_image/pinch_zoom_image.dart';

class MTG_Economics extends StatefulWidget {
  @override
  _MTG_EconomicsState createState() {
    return new _MTG_EconomicsState();
  }
}

class _MTG_EconomicsState extends State<MTG_Economics> with SingleTickerProviderStateMixin {

  TabController controller;

  @override
  void initState() {

    controller = new TabController(length: 1, vsync: this);

    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return SafeArea(
      child: ClipRRect(
        borderRadius: BorderRadius.only(
            topLeft: Radius.circular(25.0), topRight: Radius.circular(25.0)),
        child: new Scaffold(

          appBar: new TabBar(
            indicatorColor: Colors.black87,
            indicatorSize: TabBarIndicatorSize.label,
            unselectedLabelColor: Colors.grey,
            labelColor: TopicButtonArray().ColorTheme[3],
            controller: controller,

            tabs: <Widget>[
              new Tab(
                icon: new Icon(Icons.description, color:  TopicButtonArray().ColorTheme[1],),
                text:  "View",
              ),


            ],


          ),




          body: new TabBarView(

            controller: controller,
            children: <Widget>[

              new Questions(), //If you calling it from a different page use PageOne.PageOne(),



            ],

          ),


        ),
      ),
    );

  }

}

class Questions extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return  new ListView(

      children: <Widget>[




        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-025.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-026.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-027.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-028.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-029.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-030.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-031.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-032.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-033.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-034.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-035.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-036.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-037.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-038.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-039.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-040.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-041.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-042.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-043.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-044.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-045.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-046.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-047.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-048.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-049.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-050.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-051.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-052.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-053.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-054.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-055.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-056.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-057.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-058.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-059.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-060.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-061.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-062.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-063.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-064.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-065.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-066.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-067.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-068.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-069.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-070.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-071.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-072.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-073.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-074.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-075.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-076.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-077.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-078.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-079.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-080.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-081.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-082.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-083.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-084.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-085.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-086.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-087.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-088.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-089.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-090.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-091.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-092.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-093.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-094.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-095.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-096.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-097.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-098.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-100.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-101.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-102.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-103.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-104.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-105.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-106.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-107.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-108.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-109.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-110.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-111.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-112.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-113.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-114.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-115.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-116.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-117.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-118.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-119.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-120.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-121.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-122.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-123.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-124.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-125.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-126.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-127.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-128.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-129.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-130.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-131.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-132.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-133.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-134.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-135.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-136.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-137.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-138.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-139.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-140.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-141.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-142.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-143.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-144.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-145.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-146.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-147.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-148.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-149.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-150.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-151.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-152.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-153.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-154.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-155.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-156.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-157.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-158.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-159.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-160.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-161.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-162.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-163.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-164.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-165.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-166.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-167.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-168.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-169.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-170.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-171.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-172.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-173.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-174.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-175.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-176.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-177.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-178.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-179.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-180.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-181.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-182.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-183.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-184.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-185.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-186.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-187.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-188.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-189.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-190.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-191.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-192.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-193.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-194.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-195.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-196.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-197.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-198.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-199.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-200.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-201.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-202.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-203.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-204.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-205.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-206.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-207.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-208.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-209.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-210.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-211.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-212.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-213.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-214.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-215.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-216.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-217.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-218.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-219.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-220.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-221.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-222.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-223.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-224.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-225.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-226.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-227.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-228.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-229.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-230.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-231.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-232.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-233.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-234.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-235.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-236.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-237.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-238.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-239.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-240.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-241.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-242.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-243.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-244.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-245.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-246.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-247.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-248.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-249.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-250.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Economics/MTG_Economics-251.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),

      ],
    );
  }

}




