import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'ClassArrays/TopicButtonArray.dart';
import 'package:pinch_zoom_image/pinch_zoom_image.dart';

class MTG_Accounting extends StatefulWidget {
  @override
  _MTG_AccountingState createState() {
    return new _MTG_AccountingState();
  }
}

class _MTG_AccountingState extends State<MTG_Accounting> with SingleTickerProviderStateMixin {

  TabController controller;

  @override
  void initState() {

    controller = new TabController(length: 1, vsync: this);

    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return SafeArea(
      child: ClipRRect(
        borderRadius: BorderRadius.only(
            topLeft: Radius.circular(25.0), topRight: Radius.circular(25.0)),
        child: new Scaffold(

          appBar: new TabBar(
            indicatorColor: Colors.black87,
            indicatorSize: TabBarIndicatorSize.label,
            unselectedLabelColor: Colors.grey,
            labelColor: TopicButtonArray().ColorTheme[3],
            controller: controller,

            tabs: <Widget>[
              new Tab(
                icon: new Icon(Icons.description, color:  TopicButtonArray().ColorTheme[1],),
                text:  "View",
              ),


            ],


          ),




          body: new TabBarView(

            controller: controller,
            children: <Widget>[

              new Questions(), //If you calling it from a different page use PageOne.PageOne(),



            ],

          ),


        ),
      ),
    );

  }

}

class Questions extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return  new ListView(

      children: <Widget>[




        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-016.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-017.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-018.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-019.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-020.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-021.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-022.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-023.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-024.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-025.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-026.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-027.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-028.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-029.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-030.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-031.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-032.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-033.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-034.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-035.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-036.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-037.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-038.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-039.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-040.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-041.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-042.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-043.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-044.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-045.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-046.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-047.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-048.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-049.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-050.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-051.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-052.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-053.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-054.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-055.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-056.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-057.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-058.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-059.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-060.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-061.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-062.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-063.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-064.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-065.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-066.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-067.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-068.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-069.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-070.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-071.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-072.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-073.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-074.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-075.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-076.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-077.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-078.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-079.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-080.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-081.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-082.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-083.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-084.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-085.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-086.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-087.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-088.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-089.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-090.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-091.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-092.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-093.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-094.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-095.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-096.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-097.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-098.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-100.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-101.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-102.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-103.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-104.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-105.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-106.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-107.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-108.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-109.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-110.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-111.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-112.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-113.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-114.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-115.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-116.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-117.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-118.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-119.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-120.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-121.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-122.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-123.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-124.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-125.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-126.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-127.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-128.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-129.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-130.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-131.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-132.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-133.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-134.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-135.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-136.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-137.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-138.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-139.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-140.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-141.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-142.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-143.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-144.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-145.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-146.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-147.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-148.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-149.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-150.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-151.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-152.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-153.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-154.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-155.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-156.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-157.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-158.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-159.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-160.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-161.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-162.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-163.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-164.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-165.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-166.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-167.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-168.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-169.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-170.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-171.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-172.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-173.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-174.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-175.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-176.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-177.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-178.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-179.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-180.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-181.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-182.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),
        PinchZoomImage(image:  CachedNetworkImage(imageUrl: 'http://matriclive.com/new_feature/MTG/MTG_Accounting/MTG_Accounting-183.png',placeholder: (context, url) => new Image.asset('assets/ui_assets/preloader3.gif',),errorWidget: (context, url, error) => new Image.asset('assets/ui_assets/default_error.png',width: 60,height: 60,),),zoomedBackgroundColor: Color.fromRGBO(240, 240, 240, 1.0),hideStatusBarWhileZooming: true,),


      ],
    );
  }

}




